// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkGtnoOb4XUQYTNaQx5eM15pr2828bus',
    appId: '1:21657212241:web:0df3a5f57d30ed0be7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    authDomain: 'edueire-a3dc3.firebaseapp.com',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    measurementId: 'G-HL2TX288XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhSCemIzA-rqxivM4lKsAw0wgvAGRfyKU',
    appId: '1:21657212241:android:2152f466e41eb766e7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyaHauuERW1XfrllAJMrSXkYTAHYmMZ1s',
    appId: '1:21657212241:ios:4c891f55be35517ae7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    iosClientId: '21657212241-hktcnpvhl4fv2pbttbticpf1tfvu8elv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyaHauuERW1XfrllAJMrSXkYTAHYmMZ1s',
    appId: '1:21657212241:ios:4c891f55be35517ae7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    iosClientId: '21657212241-hktcnpvhl4fv2pbttbticpf1tfvu8elv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduEireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkGtnoOb4XUQYTNaQx5eM15pr2828bus',
    appId: '1:21657212241:web:33503377b7762334e7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    authDomain: 'edueire-a3dc3.firebaseapp.com',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    measurementId: 'G-R4M3XELYNZ',
  );

}