name: college_chatbot
description: A chatbot for Irish secondary school students about college and grants.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  url_launcher: ^6.1.10
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - chatbot_api.env
    - assets/edu_eire_logo.png
    - assets/menu.png
    - assets/back_arrow.png