name: edueire2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9  # Use the latest version at the time
  cupertino_icons: ^1.0.2
  csv: ^5.0.2

  # Core packages
  http: ^1.2.1
  xml: ^6.5.0
  collection: ^1.18.0
  intl: ^0.20.2

  # Env & utilities
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.2.3
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1

  # Fonts & UI
  google_fonts: ^6.1.0
  provider: ^6.1.5
  
  # Firebase
  
  google_sign_in: ^6.1.5
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  cloud_functions: ^5.6.1 
  # Validation
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - chatbot_api.env
    - assets/fonts/
    - assets/chatbot/
    - assets/chatbot/edu_eire_logo.png  # ✅ SUSI Calculator logo
    - assets/edu_eire_logo.png
    - assets/cao_list_25.csv
    - assets/cao_search/
    - assets/g-logo.png


  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic

        - asset: assets/calendar/fonts/NotoSans-VariableFont_wdth,wght.ttf
        - asset: assets/calendar/fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf
          style: italic