<<<<<<< HEAD
// lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by hand — fill in your own values from
/// Firebase console → Project settings → Your apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return webOptions;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidOptions;
      case TargetPlatform.iOS:
        return iosOptions;
      case TargetPlatform.macOS:
        return macosOptions;
      case TargetPlatform.windows:
        return windowsOptions;
      case TargetPlatform.linux:
        return linuxOptions;
=======
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
>>>>>>> e0b4353cf7ba5b3fecaec3524f9d21f0f5e54769
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

<<<<<<< HEAD
  static const FirebaseOptions webOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    authDomain: 'your-project-id.firebaseapp.com',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    messagingSenderId: '1234567890',
    appId: '1:1234567890:web:abcdef123456',
    measurementId: 'G-MEASUREID',
  );

  static const FirebaseOptions androidOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions iosOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: '1234567890-abcdefg.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.yourapp',
  );

  static const FirebaseOptions macosOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:macos:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: '1234567890-abcdefg.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.yourapp',
  );

  static const FirebaseOptions windowsOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:windows:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions linuxOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:linux:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
=======
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkGtnoOb4XUQYTNaQx5eM15pr2828bus',
    appId: '1:21657212241:web:0df3a5f57d30ed0be7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    authDomain: 'edueire-a3dc3.firebaseapp.com',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    measurementId: 'G-HL2TX288XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhSCemIzA-rqxivM4lKsAw0wgvAGRfyKU',
    appId: '1:21657212241:android:773de07237756201e7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyaHauuERW1XfrllAJMrSXkYTAHYmMZ1s',
    appId: '1:21657212241:ios:884212f4c068d2a5e7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    iosClientId: '21657212241-bh55svpmhnabaohrqmatfnht9on4k0h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.edueire2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyaHauuERW1XfrllAJMrSXkYTAHYmMZ1s',
    appId: '1:21657212241:ios:884212f4c068d2a5e7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    iosClientId: '21657212241-bh55svpmhnabaohrqmatfnht9on4k0h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.edueire2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUkGtnoOb4XUQYTNaQx5eM15pr2828bus',
    appId: '1:21657212241:web:4fd352ee174faefce7af70',
    messagingSenderId: '21657212241',
    projectId: 'edueire-a3dc3',
    authDomain: 'edueire-a3dc3.firebaseapp.com',
    storageBucket: 'edueire-a3dc3.firebasestorage.app',
    measurementId: 'G-SD1JQ9THN0',
  );

}
>>>>>>> e0b4353cf7ba5b3fecaec3524f9d21f0f5e54769
