// lib/firebase_options.dart

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated by hand — fill in your own values from
/// Firebase console → Project settings → Your apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return webOptions;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return androidOptions;
      case TargetPlatform.iOS:
        return iosOptions;
      case TargetPlatform.macOS:
        return macosOptions;
      case TargetPlatform.windows:
        return windowsOptions;
      case TargetPlatform.linux:
        return linuxOptions;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    authDomain: 'your-project-id.firebaseapp.com',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    messagingSenderId: '1234567890',
    appId: '1:1234567890:web:abcdef123456',
    measurementId: 'G-MEASUREID',
  );

  static const FirebaseOptions androidOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:android:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions iosOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: '1234567890-abcdefg.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.yourapp',
  );

  static const FirebaseOptions macosOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:macos:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: '1234567890-abcdefg.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.yourapp',
  );

  static const FirebaseOptions windowsOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:windows:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions linuxOptions = FirebaseOptions(
    apiKey: 'AIzaSyC8wRZ-NMaT-RK5ckszBfJwC1qZQuhJvlk',
    appId: '1:1234567890:linux:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
  );
}
