import 'package:flutter/material.dart';
import 'help/help_page.dart';
import 'firebase_options.dart';                // Generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // —— Global brand colour ——————————————————————————
  static const Color _brandBlue = Color(0xFF3AB6FF);

  // —— Helper that builds ThemeData for a given brightness ——
  ThemeData _buildTheme(Brightness brightness) {
    return ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: _brandBlue,
        brightness: brightness,
      ),
      scaffoldBackgroundColor:
          brightness == Brightness.light ? Colors.white : Colors.black,
      fontFamily: 'Roboto',
      appBarTheme: const AppBarTheme(
        backgroundColor: _brandBlue,
        foregroundColor: Colors.white,
        elevation: 1,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Help Page',
      debugShowCheckedModeBanner: false,
      themeMode: ThemeMode.system,            // <- follows device / main-app toggle
      theme: _buildTheme(Brightness.light),   // light scheme
      darkTheme: _buildTheme(Brightness.dark),// dark scheme
      home: HelpPage(),                       // everything inside now inherits it
    );
  }
}
